package org.openprovenance.prov.java.integration;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

import org.openprovenance.prov.java.JProvUtility;
import org.openprovenance.prov.java.component1.Entity;
import org.openprovenance.prov.java.component4.Bundle;

/**
 * Unit test for Activity class
 */
public class TraversalTest 
    extends TestCase
{
    /**
     * Create the test case
     *
     * @param testName name of the test case
     */
    public TraversalTest( String testName )
    {
        super( testName );
    }

    /**
     * @return the suite of tests being tested
     */
    public static Test suite()
    {
        return new TestSuite( TraversalTest.class );
    }
    
//    public void testDerivationParsing() {
//    	try {
//    		JProvUtility u = new JProvUtility();
//			Bundle b = u.asn2jprov("../prov-java/src/test/resources/prov/derivation-test.provn");
//			System.out.println(b);
//			WasDerivedFrom s = (WasDerivedFrom) b.getRecords().getRelations().get(2);
//			System.out.println(s.getStartElement());
//			System.out.println(s.getEndElements());
//			System.out.println(s.getGeneration());
//			System.out.println(s.getUsage());
//    	} catch (Exception e) { 
//    		e.printStackTrace();
//    	} catch (Throwable t) {
//    		t.printStackTrace();
//    	}
//    }
    
//    public void testPrimerParsing() {
//    	try {
//			JProvUtility u = new JProvUtility();
//			Bundle b = u.asn2jprov("../prov-java/src/test/resources/prov/primer.provn");
//			System.out.println(b.getRecords().getElements());
//			System.out.println(b.getRecords().getRelations());
//			System.out.println(b.getBundles());
//		} catch (Exception e) { 
//			e.printStackTrace();
//		} catch (Throwable t) {
//			t.printStackTrace();
//		}
//    }
    
    public void testParsing() {
    	try {
			JProvUtility u = new JProvUtility();
			org.openprovenance.prov.java.NSBundle b = u.convertASNToJava("../prov-java/src/test/resources/prov/test.provn");
			System.out.println(u.convertJavaToASN(b, b.getNamespaces()));
		} catch (Exception e) { 
			e.printStackTrace();
		} catch (Throwable t) {
			t.printStackTrace();
		}
    }

//    public void testUsedRelation()
//    {
//    	Bundle bundle = new Bundle();
//    	bundle.setId("ex:testBundle");
//    	
//    	// Youngest Activity
//    	Activity activity = new Activity();
//    	activity.setId("ex:a");
//    	
//    	// Activity uses this entity
//        Entity entity = new Entity();
//        entity.setId("ex:e");
//        
//        // Activity uses this entity
//        Entity entity2 = new Entity();
//        entity2.setId("ex:e2");
//        
//        // Entity2 generated by this activity
//        Activity activity2 = new Activity();
//        activity2.setId("ex:a2");
//        
//        Used used = new Used();
//        used.setId("ex:u");
//        used.setActivity(activity);
//        activity.addRelation(used);
//        used.setEntity(entity);
//        entity.addRelation(used);
//        
//        Used used2 = new Used();
//        used.setId("ex:u2");
//        used.setActivity(activity);
//        activity.addRelation(used2);
//        used.setEntity(entity2);
//        entity2.addRelation(used2);
//        
//        
//        bundle.addRecord(activity);
//        bundle.addRecord(entity);
//        bundle.addRecord(used);
//        bundle.addRecord(used2);
//        
//        Records records = bundle.getRecords();
//        Element firstElement = records.getElements().get(0);
//        
//        for (Relation r : firstElement.getRelations()) {
//        	for (Element e : r.getEndElements()) {
//        		System.out.println(e);
//        	}
//        }
//    }
//    
}
