package org.openprovenance.prov.java.component1;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

/**
 * Unit test for Entity and Activity classes with relations
 */
public class EntityActivityRelationsTests 
    extends TestCase
{
    /**
     * Create the test case
     *
     * @param testName name of the test case
     */
    public EntityActivityRelationsTests( String testName )
    {
        super( testName );
    }

    /**
     * @return the suite of tests being tested
     */
    public static Test suite()
    {
        return new TestSuite( EntityActivityRelationsTests.class );
    }

    /**
     * Test simple creation of Activity using Entity
     */
    public void testUsedRelation()
    {
    	Activity activity = new Activity();
    	activity.setId("ex:a");
    	
        Entity entity = new Entity();
        entity.setId("ex:e");
        
        Used used = new Used();
        used.setId("ex:u");
        used.setActivity(activity);
        used.setEntity(entity);
        
        used.setTime("10:00:00");
        
        assertEquals(used.getId(), "ex:u");
        assertEquals(used.getActivity(), activity);
        assertEquals(used.getEntity(), entity);
        assertEquals(used.getTime(), "10:00:00");
    }
    
    /**
     * Test simple creation of Entity generated by Activity
     */
    public void testWasGeneratedByRelation()
    {
        Entity entity = new Entity();
        entity.setId("ex:e");
        
    	Activity activity = new Activity();
    	activity.setId("ex:a");
        
        WasGeneratedBy wasGeneratedBy = new WasGeneratedBy();
        wasGeneratedBy.setId("ex:g");
        wasGeneratedBy.setEntity(entity);
        wasGeneratedBy.setActivity(activity);
        
        wasGeneratedBy.setTime("10:00:00");
        
        assertEquals(wasGeneratedBy.getId(), "ex:g");
        assertEquals(wasGeneratedBy.getEntity(), entity);
        assertEquals(wasGeneratedBy.getActivity(), activity);
        assertEquals(wasGeneratedBy.getTime(), "10:00:00");
    }

}
